Add vertical texture type and implement Chisel's SCTM
Chisel-Team/ConnectedTexturesMod pull request #138
Opened 2020-07-30 23:52 UTC by ChloeDawn

2020-08-02 22:54 UTC, Drullkus approved these changes

2020-08-12 02:59 UTC, tterrag1098 requested changes

2020-08-12 02:59 UTC, tterrag1098 commented on src/main/java/team/chisel/ctm/client/texture/render/TexturePlane.java
> +            final boolean top = logic.connected(Dir.TOP);
Really inconsistent indentation here

2020-12-13 17:58 UTC, tterrag1098 approved these changes

2020-12-13 17:59 UTC, merged